name: CI

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:

    name: Deploy to Google App Engine

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: go version

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::621271098372:role/davinci-song-chat-server-role
          role-session-name: davinci-song-chat-server-role

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Create text file
        run: |
          echo "Hello, this is a test file from GitHub Actions!" > message.txt          

      - name: Copy binary to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i id_rsa message.txt ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/davinci/message.txt
#          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} 'sudo systemctl restart myapp.service'

