name: CI

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:

    name: Deploy to Google App Engine

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - name: Create text file
      run: |
        echo "Hello, this is a test file from GitHub Actions!" > message.txt

    - name: Copy text file to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ./message.txt ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/

